apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-app-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus-operator
    release: prometheus-operator
spec:
  endpoints:
    - interval: 10s
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      prometheus-monitored: "true"
