apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    prometheus-monitored: "true"
spec:
  type: NodePort
  selector:
    app: myservice
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
