apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
      - name: myservice-container
        image: shestera/scaletestapp
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "30Mi"
          requests:
            memory: "20Mi"
